version: '3.1'

services:
  db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_HOST=root
      - MYSQL_DATABASE=kuna_db
      - MYSQL_ROOT_PASSWORD=19293119
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  db_data:

